replicaCount: 1
image:
  repository: builditdigital/style-guide
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 500m
    memory: 96Mi
  requests:
    cpu: 50m
    memory: 48Mi

